version: '3.6'
services:
  web:
    build: ./frontend
    depends_on:
      - "api"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
       - /app/node_modules
  api:
    build: ./backend
    depends_on:
      - "db"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:bakayaro123@db:5432/test
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./backend:/pyapp 

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bakayaro123
      POSTGRES_DB: test
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data